Jonathan development
chanjonathan/SoftwareProductSprint pull request #1
Opened 2022-05-31 20:15 UTC by chanjonathan

Add text content and image on webpage

2022-06-01 17:53 UTC, EvanJuV commented on portfolio/src/main/webapp/index.html
> +            <li>Will determine the ratio of conformers in the oddly specific scenario that you have thousands of methylcylcohexanes in a .gro file.</li>
Probably a typo in "methylcylcohexanes". Should it be methylcyclohexane?

2022-06-01 17:57 UTC, EvanJuV approved these changes

2022-06-16 17:57 UTC, chanjonathan commented
comment

2022-06-17 17:07 UTC, EvanJuV requested changes
Very nice Jonathan! 

I think generally speaking, you'd want to merge your PR once it's approved. If you haven't already noticed, the changes you pushed recently were added to this PR. 

Pushing new commits to the same PR makes sense if you're making changes to address comments, but generally you'd like to have one PR per feature. A feature is a relatively subjective term, but in our case we can map it to the work been done each week. In the industry it is usually mapped to an actual feature (e.g. bug fix, feature request, refactor, cleanup, etc.).

Other than that, LGTM! Please push changes addressing comments.

2022-06-18 03:25 UTC, chanjonathan commented on portfolio/pom.xml
> +    <groupId>com.google.code.gson</groupId>
fixed

2022-06-18 03:25 UTC, chanjonathan commented on portfolio/pom.xml
> +    <groupId>com.google.code.gson</groupId>
fixed

2022-06-22 08:07 UTC, chanjonathan commented
Fixes applied

2022-06-27 17:31 UTC, EvanJuV approved these changes
LGTM!

2022-06-30 22:01 UTC, merged